CREATE TABLE nfe (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    service_order_id BIGINT,
    numero INT NOT NULL,
    serie INT NOT NULL DEFAULT 1,
    chave VARCHAR(44),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    ambiente INT NOT NULL DEFAULT 2,
    natureza_operacao VARCHAR(60) NOT NULL,
    xml_enviado LONGTEXT,
    xml_retorno LONGTEXT,
    protocolo VARCHAR(20),
    data_emissao DATETIME NOT NULL,
    data_autorizacao DATETIME,
    motivo_rejeicao VARCHAR(500),
    dest_nome VARCHAR(60),
    dest_cpf_cnpj VARCHAR(14),
    dest_ie VARCHAR(18),
    dest_email VARCHAR(60),
    dest_logradouro VARCHAR(60),
    dest_numero VARCHAR(10),
    dest_bairro VARCHAR(60),
    dest_municipio VARCHAR(60),
    dest_uf VARCHAR(2),
    dest_cep VARCHAR(8),
    total_produtos DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_desconto DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_nfe DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    forma_pagamento VARCHAR(20),
    valor_pago DECIMAL(10,2),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_nfe_company FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT fk_nfe_service_order FOREIGN KEY (service_order_id) REFERENCES service_orders(id)
);

CREATE TABLE nfe_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nfe_id BIGINT NOT NULL,
    numero_item INT NOT NULL,
    codigo_produto VARCHAR(60),
    descricao VARCHAR(120) NOT NULL,
    ncm VARCHAR(8),
    cfop VARCHAR(4) NOT NULL,
    unidade VARCHAR(6) NOT NULL DEFAULT 'UN',
    quantidade DECIMAL(11,4) NOT NULL,
    valor_unitario DECIMAL(11,4) NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    csosn VARCHAR(3),
    icms_aliquota DECIMAL(5,2),
    icms_valor DECIMAL(10,2),
    pis_cst VARCHAR(2),
    pis_valor DECIMAL(10,2),
    cofins_cst VARCHAR(2),
    cofins_valor DECIMAL(10,2),
    CONSTRAINT fk_nfe_item_nfe FOREIGN KEY (nfe_id) REFERENCES nfe(id)
);
