CREATE TABLE parts (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    internal_code        VARCHAR(50)   NOT NULL UNIQUE,
    description          VARCHAR(300)  NOT NULL,
    manufacturer_code    VARCHAR(100),
    current_stock        INT           NOT NULL DEFAULT 0,
    minimum_stock        INT           NOT NULL DEFAULT 0,
    average_cost         DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    sale_price           DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    unit                 VARCHAR(20)   NOT NULL DEFAULT 'UN',
    category             VARCHAR(100),
    barcode              VARCHAR(50),
    location             VARCHAR(100),
    ncm                  VARCHAR(20),
    supplier_id          BIGINT,
    status               VARCHAR(20)   NOT NULL DEFAULT 'NORMAL',
    last_movement_at     TIMESTAMP,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_parts_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
